[versions]
agp = "8.12.1"
kotlin = "2.0.21"

coreKtx = "1.10.1"
appcompat = "1.6.1"
material = "1.10.0"
recyclerview = "1.3.2"
firebase-appdist = "5.1.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
firebase-appdist = { id = "com.google.firebase.appdistribution", version.ref = "firebase-appdist" }
